const ActionsTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCESS: "LOGIN_SUCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  UPDATE_START: "UPDATE_START",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE",
  LOGOUT: "LOGOUT",
};

export default ActionsTypes;
